name: deploy
 
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: ["18.15.0"]
 
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379
 
    env:
      NODE_ENV: ci
      PORT: 3000
 
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          # Install system dependencies for Puppeteer
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          npm install --legacy-peer-deps
          npm run build
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      - name: Start server
        run: |
          nohup npm run start &
          sleep 5
          # Wait for server to be ready
          timeout 30 bash -c 'until curl -f http://localhost:3000; do sleep 1; done'
      - name: Run tests
        run: npm run test